# -*- coding: utf-8 -*-
"""car_selection.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1LOpFFCVx7gMIkE8WYj1ZrsSPOp813lKc
"""

import pandas as pd

df = pd.read_csv("car_search.csv")

df.head()